apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

secretGenerator:
  - name: organization-secret
    envs:
      - env.properties

generatorOptions:
  disableNameSuffixHash: true

resources:
  - "../../../base/organization"